const express=require('express');
const cors=require('cors');
const bodyParser = require('body-parser');
const router = require('./routes/routing');
const app=express();
app.use(cors());
app.use(bodyParser.urlencoded({extended: true}));
app.use(bodyParser.json());
app.use('/',router);
app.listen(3000);
console.log("Server started at port 3000!");
